### ISSUE TITLE
create_organization("name") TypeError: string indices must be integers

### ISSUE THREAD

**Issue by patsevanton** [m0nhawk/grafana_api#77]
Hello! Thanks for grafana_api.
How correct create organization ?

```
grafana_api.organization.create_organization("name")
```

Output
```
Traceback (most recent call last):
  File "/home/user/russianpost/service/python-tools-adapter/Grafana/manage-grafana-by-api.py", line 90, in <module>
    grafana_api.organization.create_organization("name")
  File "/usr/local/lib/python3.6/dist-packages/grafana_api/api/organization.py", line 35, in create_organization
    r = self.api.POST(create_orgs_path, json={"name": organization["name"]})
TypeError: string indices must be integers

Process finished with exit code 1
```

**Comment by patsevanton** [comment]
```
grafana_api.organization.create_organization({"name":"erwt422w"})
```
output
```
grafana_api.grafana_api.GrafanaClientError: Client Error 409: Organization name taken
```
